# Use the official Python image
FROM python:3.11

# Expose the specified port
EXPOSE 12000

# Create and set the working directory
WORKDIR /app

# Copy the local app files to the container
COPY ./src/myftp /app

# Create files with random content in the /server directory
RUN mkdir /server
RUN dd if=/dev/urandom of=/server/file1.txt bs=1024 count=10
RUN dd if=/dev/urandom of=/server/image1.png bs=1024 count=50

# Start your Python application
#CMD python server.py --port_number 12000 --debug 1
