# Use the official Python image
FROM python:3.11

# Expose the specified port
EXPOSE 12000

# Create and set the working directory
WORKDIR /client

# Copy the local  client to the container
RUN mkdir /client_directory
RUN dd if=/dev/urandom of=/client_directory/file_local.txt bs=1024 count=10
RUN dd if=/dev/urandom of=/client_directory/image_local.png bs=1024 count=50

# Start your Python application
#CMD python client.py --debug 1
